import { parseCaptionDate } from '../../scripts/photo-date.mjs';
import type { BuiltPhoto } from '../../scripts/photos-lib.mjs';

export type Photo = BuiltPhoto;

/** Your Instagram profile URL. Empty hides the "Follow on Instagram" link. */
export const INSTAGRAM_URL = '';

/** Source filename (as in photos-src/, e.g. "me.jpg") to use as the round avatar. Empty uses the newest photo. */
export const AVATAR_PHOTO = '';

// The manifest is generated by `npm run photos` (it runs before dev, test, typecheck and build). A glob keeps the app working if it is missing.
const manifests = import.meta.glob<Photo[]>('./photos.generated.json', { eager: true, import: 'default' });

/** Newest first. Built by scripts/build-photos.mjs. */
export const photos: Photo[] = Object.values(manifests)[0] ?? [];

export function avatarFor(list: Photo[], filename = AVATAR_PHOTO): Photo | undefined {
  return list.find((photo) => photo.file === filename) ?? list[0];
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

/** "2026-09" -> "Sep 2026", "2026-09-14" -> "14 Sep 2026", "2026" -> "2026". Anything unparseable is shown as written. */
export function formatPhotoDate(value: string): string {
  if (Number.isNaN(parseCaptionDate(value))) return value;
  const [year, month, day] = value.split('-');
  if (!month) return year;
  const name = MONTHS[Number(month) - 1];
  return day ? `${Number(day)} ${name} ${year}` : `${name} ${year}`;
}
